### ISSUE TITLE
Can we integrate this into a discord bot somehow?

### ISSUE THREAD

**Issue by sakshatshinde** [bradtraversy/alexis_speech_assistant#3]
It would be cool if you show us how to integrate this gTTS API into a discord bot which could be like an Voice Channel assistant. Especially for playing music and stuff.

**Comment by sakshatshinde** [comment]
A library called [discord.py](https://discordpy.readthedocs.io/en/latest/) exists which allows us to make a bot and get started pretty easily.

**Comment by jcrommar** [comment]
why not just do it?
